services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700M

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 60M

